# Generated by Django 3.2.3 on 2021-06-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_saved_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_recipes',
            name='likes',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
